### ISSUE TITLE
Module level app.go

### ISSUE THREAD

**Issue by marbar3778** [cosmos/modules#8]
```
uhhhh why do we have an app defined on the module ? I don't see the need to define one for each module.

Also, the NFT module is not stable. It still has performance issues that need to be resolved so I'd move it to beta
```
concern from @fedekunze 
https://github.com/cosmos/modules/pull/1#discussion_r332901893

**Comment by alexanderbez** [comment]
> uhhhh why do we have an app defined on the module ? I don't see the need to define one for each module.

Well, you cannot have a single app because different modules may conflict with each other in terms of functionality and domain (e.g. `x/poa` and `x/pow` or `x/staking*`). So the need for multiple apps is obvious from this case. The problem then is how and where these apps live and how are they constructed as to allow the best possible dev-ux and configuration.
